name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-lint-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Lint Check
      run: ./gradlew lint

    - name: Save Lint Report
      uses: actions/upload-artifact@v1
      with:
        name: lint-result
        path: app/build/reports/lint-results-debug.html

    - name: Execute Unit Tests
      run: ./gradlew test

    - name: Save Unit Test Report
      uses: actions/upload-artifact@v1
      with:
        name: unit-test-result
        path: app/build/reports/tests/testDebugUnitTest/

    - name: Instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck --stacktrace

    - name: Upload Reports
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: app/build/reports
